# Generated by Django 5.0.6 on 2024-07-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataroom", "0002_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="filename",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
