# Generated by Django 5.0.6 on 2024-07-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataroom", "0003_alter_file_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default="Default Company", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="cnpj",
            field=models.CharField(
                default="00.000.000/0000-00", max_length=18, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(default="Default Company", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="(00) 0000-0000", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="social_reason",
            field=models.CharField(default="Default Social Reason", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consideration",
            name="consideration_filename",
            field=models.FileField(upload_to="considerations/"),
        ),
        migrations.AlterField(
            model_name="consideration",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="considerations",
                to="dataroom.file",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
