# Generated by Django 5.0.6 on 2024-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataroom", "0005_alter_user_address_alter_user_cnpj_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="action",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("download", "Download"),
                    ("upload_consideration", "Upload Consideration"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cnpj",
            field=models.CharField(
                default="00.000.000/0000-00", max_length=18, unique=True
            ),
        ),
    ]
