# Generated by Django 5.0.6 on 2024-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataroom", "0006_alter_log_action_alter_user_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(default="Default Position", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="representative_name",
            field=models.CharField(default="Default Representative", max_length=255),
        ),
    ]
