# Generated by Django 5.0.6 on 2024-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataroom", "0007_user_position_user_representative_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
