# Generated by Django 3.2 on 2024-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0012_auto_20240703_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consideration',
            name='consideration_data',
            field=models.BinaryField(blank=True, default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(blank=True, default=b'', null=True),
        ),
    ]
