# Generated by Django 3.2 on 2024-07-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0015_auto_20240703_2047'),
        ('dataroom', '0016_alter_consideration_consideration_data'),
    ]

    operations = [
    ]
