# Generated by Django 3.2 on 2024-07-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0018_auto_20240703_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(),
        ),
    ]
